name: Build macOS .app and .dmg for MyztrixAgent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Strip Windows-only dependencies (macOS safe)
        run: |
          grep -Ev "pywin32|win-precise-time|win32_setctime" myztrix/requirements.txt > myztrix/requirements-macos.txt
          python -m pip install --upgrade pip
          pip install -r myztrix/requirements-macos.txt py2app

      - name: Build macOS .app using py2app
        run: |
          cd myztrix
          python setup.py py2app

      - name: Create .dmg
        run: |
          mkdir -p myztrix/dist_dmg
          hdiutil create myztrix/dist_dmg/MyztrixAgent.dmg \
            -volname "MyztrixAgent" \
            -srcfolder myztrix/dist/MyztrixAgent.app \
            -ov -format UDZO

      - name: Upload .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyztrixAgent-dmg
          path: myztrix/dist_dmg/MyztrixAgent.dmg
